#######################################################################################
# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MK Dynamics
author: Mark Khusid
logo: images/spacey.jpg

exclude_patterns: [build, "FORD.md", "README.md", "ford.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  stderr_output: "remove"
  timeout: -1 # never timeout
  exclude_patterns: [build, "FORD.md", "README.md", "ford.md"]
    

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# References
#references:
#  MKD_Fortran_Book: https://www.mkdynamics.net/current_projects/Fortran/intro.html

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "images/spacey.jpg"
  use_multitoc_numbering: false
  analytics:
    google_analytics_id: G-BZ3C1QVH0B

# Information about where the book exists on the web
repository:
  url: https://github.com/markkhusid/MKDynamics_Website_V2  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  jupyterhub_url: "https://datahub.berkeley.edu"
  colab_url: "https://colab.research.google.com"
  thebe: true

parse:
  myst_substitutions:
    sub3: My _global_ value!
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

sphinx:
  #extra_extensions:
  #  - sphinx.ext.intersphinx

  config:
    # Enable all intersphinx references
    #intersphinx_disabled_reftypes: [None]

    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sd:
        - https://sphinx-design.readthedocs.io/en/latest
        - null

    #latex_elements:
    #  sphinxsetup: "iconpackage=fontawesome"

    html_show_copyright: false

    #intersphinx_mapping: 
    #  MKD_Fortran_Book: 
    #  - "../markkhusid-MKDWWW_Fortran_Jupyter_Book/_build/html/"
    #  - null
    
    
# Enable InterSphinx reference types

# Enable InterSphinx for cross-referencing between books
#intersphinx:
#  MKD_Fortran_Book: https://www.mkdynamics.net/current_projects/Fortran/intro.html


# Use the PyData Sphinx Theme
html_theme: pydata_sphinx_theme

# Theme options
html_theme_options:
  # Set the color theme (light, dark, or auto)
  color_theme: dark
