# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MK Dynamics
author: Mark Khusid
logo: images/spacey.jpg

exclude_patterns: [build, "FORD.md", "README.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  exclude_patterns: [build, "FORD.md", "README.md"]
    

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# References
#references:
#  MKD_Fortran_Book: https://www.mkdynamics.net/current_projects/Fortran/intro.html

# Information about where the book exists on the web
repository:
  url: https://github.com/markkhusid/MKDynamics_Website_V2  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "images/spacey.jpg"
  use_multitoc_numbering: false

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: "https://mybinder.org"
  jupyterhub_url: "https://datahub.berkeley.edu"
  colab_url: "https://colab.research.google.com"
  thebe: true
  
  analytics:
    google_analytics_id: G-G0DPEVV9KG

sphinx:
  #extra_extensions:
  #  - sphinx.ext.intersphinx

  config:
    # Enable all intersphinx references
    #intersphinx_disabled_reftypes: [None]

    html_show_copyright: false
    
    #intersphinx_mapping: 
    #  MKD_Fortran_Book: 
    #  - "../markkhusid-MKDWWW_Fortran_Jupyter_Book/_build/html/"
    #  - null
    
    
# Enable InterSphinx reference types

# Enable InterSphinx for cross-referencing between books
#intersphinx:
#  MKD_Fortran_Book: https://www.mkdynamics.net/current_projects/Fortran/intro.html


# Use the PyData Sphinx Theme
html_theme: pydata_sphinx_theme

# Theme options
html_theme_options:
  # Set the color theme (light, dark, or auto)
  color_theme: dark
