name = "Section_Sum_Values_No_Infinite"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Sum_Values_No_Infinite"
source-dir="app"
main="sum_values_no_infinite.f90"
