name = "Section_Strings_Assignment"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Strings_Assignment"
source-dir="app"
main="str_assignment.f90"
