name = "Section_Arrays_Normalize"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Arrays_Normalize"
source-dir="app"
main="section_arrays_normalize.f90"
