name = "Section_Towers_Of_Hanoi"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Towers_Of_Hanoi"
source-dir="app"
main="towers_of_hanoi.f90"
