name = "Section_Bit_Manipulations_Bit_Count"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
csv-fortran = {git="https://github.com/jacobwilliams/csv-fortran.git"}

[[executable]]
name="Section_Bit_Manipulations_Bit_Count"
source-dir="app"
main="section_bit_manipulations_bit_count.f90"
