name = "Section_Random_Integers"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[[executable]]
name="Section_Random_Integers"
source-dir="app"
main="random_integers.f90"
