name = "Section_Examples_Sine_Wave"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
neural-fortran = { git="https://github.com/modern-fortran/neural-fortran.git" }

[[executable]]
name="Section_Examples_Sine_Wave"
source-dir="app"
main="section_examples_sine_wave.f90"

